name: Build Windows Latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ./DashboardIotHome/DashboardIotHome.csproj
    - name: Build
      run: dotnet build  ./DashboardIotHome/DashboardIotHome.csproj --configuration Release --no-restore
